### PR TITLE
User-interface

### PR DESCRIPTION
**Pull request by babs257**
This is the user-interface for the tic-tac-toe game project.

### CODE REVIEW

**Comment by mihrab34** [comment]
The first pull request was mistakenly merged to the development branch

**Comment by shshamim63** [comment]
## Status :ballot_box_with_check: [!! Changes Required !!] :ballot_box_with_check: 
___
Hi @babs257  and @mihrab34 :wave: ,
The messages I can see on the main.rb file  are the following:
1. A short intro of the game.
2. Asking players for their names with symbol
3. Ask player to place a move when it is his turn.
4. Display a board
5. Renders If there is a winner or a draw.
___
You have covered most of the part on the first go, awesome  job :clap: . But there are some additional messages that you forgot to add. And a simple loop which will indicate that all the repetitive messages will be placed in here, which you have covered by using a  set of comments. So please follow the instructions below to complete this milestone.
___
### :space_invader: [Mandatory Changes] :space_invader: 
1. A user can place an invalid move by accident or intentionally. So we need a message to warn user that the move he just played is invalid.
2. All these messages should perform repetitively. So a loop is needed to give an indication that 
([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)). You can try something like,
```ruby
game_on = true
while game_on
  #performs repetitive render
  if winner # and/or draw 
    game_on = false
  end
end
```
___
### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Comment by babs257** [comment]
Added Game Play Loop

**Review by whiz25 — APPROVED** [review]
## Good job :+1:
I see you have made the requested changes. Merge and proceed.

### Martin Afani

**Pull request merged**
